apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: price-oracle-airflow
requires:
  - path: namespace.yaml
  - path: secrets.yaml
  - path: configmaps.yaml
  - path: cassandra.yaml
build:
  artifacts:
    - image: price-oracle-airflow
      #TODO: point to ../.docker/airflow/Dockerfile
      context: ../airflow
      sync:
        manual:
          - src: 'dags/**/*.py'
            dest: /opt/airflow
          - src: 'assets/**/*.csv'
            dest: /opt/airflow
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: price-oracle-airflow
        remoteChart: apache-airflow/airflow
        upgradeOnChange: true
        createNamespace: true
        namespace: price-oracle
        setValueTemplates:
          images.airflow.repository: "{{.IMAGE_REPO_price_oracle_airflow}}"
          images.airflow.tag: "{{.IMAGE_TAG_price_oracle_airflow}}@{{.IMAGE_DIGEST_price_oracle_airflow}}"
        valuesFiles:
         - ../.helm/airflow/values.yaml
portForward:
- resourceType: service
  resourceName: price-oracle-airflow-webserver
  namespace: price-oracle
  port: 8080
  localPort: 8080