apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: price-oracle-grafana
deploy:
  helm:
    releases:
      - name: price-oracle-grafana
        remoteChart: grafana/grafana
        upgradeOnChange: true
        createNamespace: true
        namespace: price-oracle
portForward:
- resourceType: deployment
  resourceName: price-oracle-grafana
  namespace: price-oracle
  port: 3000
  localPort: 3000