apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db
  namespace: price-oracle
data:
  "01-init.cql": |
    
    CREATE KEYSPACE IF NOT EXISTS price_oracle
    WITH replication = {
      'class': 'SimpleStrategy',
      'replication_factor': 3
    };

    USE price_oracle;

    CREATE TABLE IF NOT EXISTS price_candlestick (
        coin text,
        close_time_date timestamp,
        close_time bigint,
        open_price double,
        high_price double,
        low_price double,
        close_price double,
        volume double,
        quote_volume double,
        period text,
        period_name text,
        PRIMARY KEY (coin, close_time)
    );


    CREATE TABLE IF NOT EXISTS indicators (
        coin text,
        close_time_date timestamp,
        ema_12 double,
        ema_26 double,
        ema_50 double,
        ema_100 double,
        ema_200 double,
        sma_5 double,
        sma_10 double,
        sma_20 double,
        sma_50 double,
        sma_100 double,
        sma_200 double,
        PRIMARY KEY (coin, close_time_date)
    );


    CREATE TABLE IF NOT EXISTS prediction (
        close_time_date timestamp,
        close_price double,
        coin text,
        model_name text,
        PRIMARY KEY (coin, model_name, close_time_date)
    );

    
    CREATE TABLE IF NOT EXISTS metrics (
        date timestamp,
        target text,
        metric_all double,
        metric_60_d double,
        metric_30_d double,
        model_name text,
        PRIMARY KEY (target, model_name, date)
    );