apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: price-oracle
build:
  artifacts:
    - image: price-oracle-airflow
      context: .
      sync:
        manual:
          - src: 'dags/**/*.py'
            dest: /opt/airflow
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: price-oracle-airflow
        remoteChart: apache-airflow/airflow
        upgradeOnChange: true
        createNamespace: true
        namespace: price-oracle
        setValueTemplates:
          images.airflow.repository: "{{.IMAGE_REPO_price_oracle_airflow}}"
          images.airflow.tag: "{{.IMAGE_TAG_price_oracle_airflow}}@{{.IMAGE_DIGEST_price_oracle_airflow}}"
        valuesFiles:
          - ./values.yaml
portForward:
- resourceType: service
  resourceName: price-oracle-airflow-webserver
  namespace: price-oracle
  port: 8080
  localPort: 8080